include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right nice_view_adapter nice_view
 # - board: seeeduino_xiao_ble
 #   shield: settings_reset
